spring:
  application:
    name: spring-boot.communication-service-v1

server:
  servlet:
    context-path: /api/communication/v1
  forward-headers-strategy: framework

application:
  sftp:
    host: 192.168.18.44
    port: 22
    user: PC
    password: 12345
    unknown-keys: true
    remote:
      directory:
        upload: /C/DEV/remoto
        download: /C/DEV/remoto

